disabled_rules: # rule identifiers to exclude from running

opt_in_rules: # some rules are only opt-in
    - closure_spacing

included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
    - Connected-iOSTests

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)

identifier_name:
    excluded:
        - id

type_name:
    excluded:
        - Id
