whitelist_rules:
    - trailing_whitespace
    - vertical_whitespace
    - opening_brace
    - closure_spacing
    - trailing_comma
    - trailing_newline

disabled_rules: # rule identifiers to exclude from running
#    - weak_delegate
    
opt_in_rules: # some rules are only opt-in

included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)

