name: SwiftLint

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, actions/* ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Install swiftlint
      run: brew install swiftlint

    - name: Lint
      run: |
        set -o pipefail \
        && swiftlint \
        | sed -E "s/$(pwd|sed 's/\//\\\//g')\///" \
        | sed -E "s/warning/error/" \
        | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 file=\1,line=\2,col=\3::\5/'

    - name: if fail
      uses: actions/github-script@v2
      if: failure()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const ref = "${{github.ref}}"
          const pull_number = Number(ref.split("/")[2])
          await github.pulls.createReview({
            ...context.repo,
            pull_number,
            body:"코드를 다시 확인해주세요. ",
            event: "REQUEST_CHANGES"
          })
          await github.pulls.update({
            ...context.repo,
            pull_number,
            state: "closed"
          })



