name: UnitTest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # push:
  #   branches: [ master, actions/** ]
  # pull_request:
  #   branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: macOS-latest
    env:
      WORKSPACE: Connected-iOS.xcworkspace
      PROJECT: Coneected-iOS.xcodeproj
      SCHEME: Connected-iOS
      SDK: iphonesimulator
      DESTINATION: platform=iOS Simulator,name=iPhone 11 Pro,OS=latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: pod install

    - name: Test
      run: |
        set -o pipefail \
        && xcodebuild clean test \
          -workspace "$WORKSPACE" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          -enableCodeCoverage YES \
        | xcpretty -c
